export const GET_QUOTES_LIST = 'GET_QUOTES_LIST';
export const GET_QUOTES_LIST_SUCCESS = 'GET_QUOTES_LIST_SUCCESS';
export const GET_QUOTES_LIST_FAILURE = 'GET_QUOTES_LIST_FAILURE';

// random quote actions

export const GET_RANDOM_QUOTE = 'GET_RANDOM_QUOTE';
export const GET_RANDOM_QUOTE_SUCCESS = 'GET_RANDOM_QUOTE_SUCCESS';
export const GET_RANDOM_QUOTE_FAILURE = 'GET_RANDOM_QUOTE_FAILURE';

// authors data actions

export const GET_AUTHORS_DATA = 'GET_AUTHORS_DATA'
export const GET_AUTHORS_DATA_SUCCESS = 'GET_AUTHORS_DATA_SUCCESS'
export const GET_AUTHORS_DATA_FAILURE = 'GET_AUTHORS_DATA_FAILURE'